### ISSUE TITLE
Make install command fails

### ISSUE THREAD

**Issue by ucefizi** [totosugito/prozilla-2.0.4#5]
After "./configure" and "make" command were successful, the "make install" command failed. I joined a screenshot from the error and the output from the command with the issue.
[make.txt](https://github.com/totosugito/prozilla-2.0.4/files/488159/make.txt)

![screenshot from 2016-09-22 20-11-48](https://cloud.githubusercontent.com/assets/8867679/18762458/be4959e4-8100-11e6-97f2-ade387b29661.png)

**Comment by jserviceorg** [comment]
you are missing ncurses devel header

**Comment by ucefizi** [comment]
Thanks, @jserviceorg, installing ncurses library solved the issue. (Solving the issue 2+ years after encountering it :p)
